// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiEqpIFgr_BW8ZHshovvOFTGDguLY5p6o',
    appId: '1:168569769977:web:fe1718b95f6dc7fa27f728',
    messagingSenderId: '168569769977',
    projectId: 'prakflutterfirebase-d33d9',
    authDomain: 'prakflutterfirebase-d33d9.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-d33d9.appspot.com',
    measurementId: 'G-M5C4EWHRGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7YsnvkeAjCqP8coFwCcAvXX37od8GDS0',
    appId: '1:168569769977:android:01a0a4f63292a3de27f728',
    messagingSenderId: '168569769977',
    projectId: 'prakflutterfirebase-d33d9',
    storageBucket: 'prakflutterfirebase-d33d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvHA7Hnp725YlyhTHpYtDaNMjet_Vm5gE',
    appId: '1:168569769977:ios:79be0fe8a7e3448d27f728',
    messagingSenderId: '168569769977',
    projectId: 'prakflutterfirebase-d33d9',
    storageBucket: 'prakflutterfirebase-d33d9.appspot.com',
    iosBundleId: 'com.example.praktikum0621102141',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvHA7Hnp725YlyhTHpYtDaNMjet_Vm5gE',
    appId: '1:168569769977:ios:79be0fe8a7e3448d27f728',
    messagingSenderId: '168569769977',
    projectId: 'prakflutterfirebase-d33d9',
    storageBucket: 'prakflutterfirebase-d33d9.appspot.com',
    iosBundleId: 'com.example.praktikum0621102141',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiEqpIFgr_BW8ZHshovvOFTGDguLY5p6o',
    appId: '1:168569769977:web:fb698bed84e04cef27f728',
    messagingSenderId: '168569769977',
    projectId: 'prakflutterfirebase-d33d9',
    authDomain: 'prakflutterfirebase-d33d9.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-d33d9.appspot.com',
    measurementId: 'G-VM8TXDZ678',
  );

}